fan_board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='home')),
    path('user/', include('users.urls', namespace='user')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
    path("", views.PostList.as_view(), name="index"),
    path('search/', views.PostList.as_view(), name='search'),
    path('post/post_create/', views.PostCreate.as_view(), name='post_create'),
    path('post/<int:post_id>/', views.PostDetail.as_view(), name="post_detail"),
    path('post/<int:post_id>/edit/', views.PostUpdate.as_view(), name='post_update'),
    path('post/<int:post_id>/delete/', views.PostDelete.as_view(), name="post_delete"),
    path('post/<int:id>/like/', views.post_like, name="post_like"),
    path('post/<int:id>/dislike/', views.post_dislike, name="post_dislike"),
    path('post/<int:post_id>/reply_add/', views.reply_add, name="reply_add"),
    path('replies/<int:reply_id>/reply_delete/', views.reply_delete, name="reply_delete"),
    path('replies/<int:reply_id>/reply_accept/', views.reply_accept, name="reply_accept"),
]

posts/models.py
from django.db import models
from django.urls import reverse
from users.models import User
from django_ckeditor_5.fields import CKEditor5Field


class Post(models.Model):
    """
    модель публикаций / объявлений
    """
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    # content = models.TextField(verbose_name='Содержание')
    content = CKEditor5Field(verbose_name='Содержание', config_name='extends', blank=True)
    created_at = models.DateTimeField(verbose_name='Создан', auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    likes = models.IntegerField(default=0, verbose_name='+')
    dislikes = models.IntegerField(default=0, verbose_name='-')
    rating = models.IntegerField(default=0, verbose_name='рейтинг')
    image = models.ImageField(verbose_name='Изображение, для новостей', blank=True)
    is_news = models.BooleanField(default=False, verbose_name='Это новость')

    class Meta:
        ordering = ('-created_at',)
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

    def __str__(self):
        return f'{self.title}'

    def like(self):
        self.likes += 1
        self.rating += 1
        self.save()

    def dislike(self):
        self.dislikes += 1
        self.rating -= 1
        self.save()

    def get_reply_count(self):
        return Reply.objects.filter(post=self).count()

    def get_view_count(self):
        return ViewPosts.objects.filter(post=self).count()

    def get_absolute_url(self):
        return reverse('posts:post_update', args=[str(self.id)])


class Category(models.Model):
    """
    Модель категорий
    """
    name = models.CharField(max_length=150)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return f'{self.name}'


class ViewPosts(models.Model):
    """
    Модель регистрации просмотра публикации
    """
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    ip_address = models.GenericIPAddressField(verbose_name='IP адрес')
    viewed_on = models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра')

    class Meta:
        ordering = ('-viewed_on',)
        indexes = [models.Index(fields=['-viewed_on'])]
        verbose_name = 'Просмотр'
        verbose_name_plural = 'Просмотры'


class Reply(models.Model):
    """
    Модель ответа на публикацию
    """
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    content = models.TextField(verbose_name='Содержание')
    created_at = models.DateTimeField(verbose_name='Создан', auto_now_add=True)
    is_accepted = models.BooleanField(default=False, verbose_name='Принят')

    class Meta:
        ordering = ('-created_at',)
        verbose_name = 'Отклик'
        verbose_name_plural = 'Отклики'

    def __str__(self):
        return f'{self.created_at.strftime("%d.%m.%Y")}: {self.content}'


class PostLikes(models.Model):
    """
    Модель регистрации лайка/дизлайка публикации
    Чтобы один и тот же пользователь не мог 100500 раз лайкать 1 объявление
    """
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    like = models.IntegerField(default=0, verbose_name='+1 / -1 лайк')

posts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Post, Reply


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'category',
            'title',
            'content',
        ]

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы под Bootstrap
        """
        super().__init__(*args, **kwargs)
        # for field in self.fields:
        #     self.fields[field].widget.attrs.update({'class': 'form-control', 'autocomplete': 'off'})
        self.fields['title'].widget.attrs.update({'class': 'form-control form-label'})
        self.fields['category'].widget.attrs.update({'class': 'form-control form-label'})

        # self.fields['content'].widget.attrs.update({'class': 'form-control django_ckeditor_5'})
        # self.fields['content'].required = False


# дополнительные свои контроли полей формы
# def clean(self):
#     cleaned_data = super().clean()
#     title = cleaned_data.get("title")
#     text = cleaned_data.get("text")
#
#     if title == text:
#         raise ValidationError(
#             "Описание не должно быть идентичным заголовку."
#         )
#
#     return cleaned_data


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = [
            'content',
        ]

posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from posts.forms import PostForm, ReplyForm
from posts.models import Post, Category, PostLikes, Reply, ViewPosts
from posts.utils import q_search, get_client_ip

from django.core.cache import cache  # импортируем наш кэш


class PostList(ListView):
    model = Post
    template_name = 'posts/post_list.html'
    ordering = '-created_at'
    paginate_by = 5
    queryset = Post.objects.filter(is_news=False)

    def get_context_data(self, **kwargs):

        category = self.request.GET.get('category', None)
        query = self.request.GET.get("q", None)

        context = super().get_context_data(**kwargs)
        context['title'] = 'Публикации'

        if category:
            context['title'] = Category.objects.get(id=category)
            context['post_list'] = Post.objects.filter(category__id=category, is_news=False)

        elif query:
            context['post_list'] = q_search(query)

        context['news_list'] = Post.objects.filter(is_news=True)

        # отзывы
        page_reply = self.request.GET.get("page_reply", 1)
        replies = Reply.objects.filter(is_accepted=True).order_by('-created_at')
        pagination = Paginator(replies, 5)
        current_page = pagination.page(int(page_reply))
        context['replies'] = current_page

        return context

    # def get_o


class PostCreate(CreateView):
    form_class = PostForm
    model = Post
    template_name = 'posts/post_edit.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title_page'] = 'Добавление публикации'
        context['categories'] = Category.objects.all()

        return context

    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            form = PostForm(request.POST)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.author = request.user
                instance.save()

                return redirect('posts:index')

        return super().get(request, *args, **kwargs)


class PostUpdate(UpdateView):
    form_class = PostForm
    model = Post
    template_name = 'posts/post_edit.html'
    pk_url_kwarg = 'post_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title_page'] = 'Изменение публикации'
        context['categories'] = Category.objects.all()

        return context

    def get_success_url(self):
        return reverse('posts:post_detail', kwargs={'post_id': self.kwargs['post_id']})


class PostDelete(DeleteView):
    model = Post
    template_name = 'posts/post_delete.html'
    success_url = '/'
    pk_url_kwarg = 'post_id'

    def get_success_url(self):
        return reverse('posts:index')


class PostDetail(DetailView):
    model = Post
    template_name = 'posts/post_detail.html'
    context_object_name = 'post'
    pk_url_kwarg = 'post_id'

    def get_object(self, *args, **kwargs):
        # Получение ip просматривающего и регистрация его как просмотревшего публикацию
        ip = get_client_ip(self.request)
        post = Post.objects.get(id=self.kwargs['post_id'])
        pk = post.pk

        if not ViewPosts.objects.filter(ip_address=ip, post_id=pk).exists():
            ViewPosts.objects.create(ip_address=ip, post_id=pk)

        obj = cache.get(f'post-{self.kwargs["post_id"]}', None)

        # если объекта нет в кэше, то получаем его и записываем в кэш
        if obj:
            obj = super().get_object(queryset=self.queryset)
            cache.set(f'post-{self.kwargs["post_id"]}', obj)

        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        post = Post.objects.get(pk=self.kwargs['post_id'])

        context['post'] = post
        context['is_authors'] = post.author = self.request.user

        context['replies'] = Reply.objects.filter(post_id=post.id, is_accepted=True)

        return context


@login_required()
def post_like(request, id, **kwargs):
    post = Post.objects.get(id=id)
    if post:
        post_likes = PostLikes.objects.filter(post=post, user=request.user).first()
        if post_likes and post_likes.like == 1:
            post_likes.delete()

            post.likes -= 1
            post.rating -= 1
            post.save()

        if not post_likes:
            post_likes = PostLikes.objects.create(post=post, user=request.user, like=1)

            post.likes += 1
            post.rating += 1
            post.save()

    return redirect(request.META.get('HTTP_REFERER'))


@login_required()
def post_dislike(request, id, **kwargs):
    post = Post.objects.get(id=id)
    if post:
        post_likes = PostLikes.objects.filter(post=post, user=request.user).first()
        if post_likes and post_likes.like == -1:
            post_likes.delete()

            post.dislikes -= 1
            post.rating += 1
            post.save()

        if not post_likes:
            post_likes = PostLikes.objects.create(post=post, user=request.user, like=-1)

            post.dislikes += 1
            post.rating -= 1
            post.save()

    return redirect(request.META.get('HTTP_REFERER'))


@login_required()
def reply_add(request, post_id, **kwargs):
    if request.method == 'POST':
        form = ReplyForm(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.post = Post.objects.get(id=post_id)
            reply.author = request.user
            if request.user == reply.post.author:
                reply.is_accepted = True
            reply.save()
            return HttpResponseRedirect(reverse('posts:post_detail', args=[reply.post.id]))
    else:
        form = ReplyForm()

    context = {
        'title': 'Home - Добавить ответ',
        'form': form
    }

    return render(request, 'posts/post_detail.html', context)


@login_required()
def reply_delete(request, reply_id):
    reply = Reply.objects.get(id=reply_id)
    reply.delete()

    return redirect(request.META.get('HTTP_REFERER'))


@login_required()
def reply_accept(request, reply_id):
    reply = Reply.objects.get(id=reply_id)
    if reply:
        reply.is_accepted = True
        reply.save()

    return redirect(request.META.get('HTTP_REFERER'))

templates/posts/post_delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="container text-white" >
        <h4>Удаление публикации</h4>
        <hr>
        <form action="" method="post">
            {% csrf_token %}
            <p>Удаляем {{ object }}"?</p>
            <button type="submit" class="btn btn-danger">
                Удалить
            </button>
            <a class="btn btn-dark" href="{{ request.META.HTTP_REFERER }}">Назад</a>
        </form>
    </div>
{% endblock content %}

templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% load custom_tags %}

{% block title %}
    Добавление публикации
{% endblock title %}

{% block content %}

    <article class="story">
        <div class="container">
            <div class="story__main">
                <header class="story__header">
                    <div class="story__user">
                        <div class="story__user-info">
                            <a class="story__user-link user__nick" href="#">
                                <div class="avatar avatar_small">
                                <span class="avatar__inner">
                                    {% if post.author.image %}
                                        <img src="{{ post.author.image.url }}" alt=""
                                             class="image-loaded avatar avatar_small">
                                    {% else %}
                                        <img src="{% static 'img/baseavatar.jpg' %}" alt=""
                                             class="image-loaded avatar avatar_small">
                                    {% endif %}

                                </span>
                                </div>
                                {{ post.author }}
                            </a>
                            <div>
                                <time datetime="{{ post.created_at }}"
                                      class="caption story__datetime">{{ post.created_at }}</time>
                            </div>

                        </div>
                    </div>
                    <h4 class="story__title">
                        <h4> {{ post.title }} </h4>
                    </h4>
                </header>
                <div class="story__content-wrapper">
                    <div class="story__content story__typography" style="display: block">
                        <div class="story__content-inner">
                            <div class="story-block story-block_type_text">
                                <p>{{ post.content|safe }}</p>
                            </div>
                        </div>
                    </div>

                    <div class="story__footer" style="font-size: 30px">
                        <div class="story__tools">
                            <div class="comment">
                                <i class="fa fa-comments"></i>
                                <span style="margin-left: 10px; line-height: 15px;"> {{ post.get_reply_count }} </span>
                            </div>
                            <div class="view">
                                <i style="margin-left: 10px;" class="fa fa-eye"></i>
                                <span style="margin-left: 10px; line-height: 15px;"
                                      class="story__views-count">{{ post.get_view_count }}</span>
                            </div>
                        </div>
                        <div>
                            {% if is_authors %}
                                <a class="btn btn-light" href="{% url 'posts:post_update' post.id %}">Изменить</a>
                                <a class="btn btn-light" href="{% url 'posts:post_delete' post.id %}">Удалить</a>
                            {% endif %}
                            <a class="btn btn-light" href="{{ request.META.HTTP_REFERER }}">Назад</a>
                        </div>
                    </div>
                </div>

            </div>
            <div id="replies" class="story-comments section-group">
                <div class="story-comments__all section-group">
                    <form class="d-flex" action="{% url 'posts:reply_add' post.id %}" method="post">
                        {% csrf_token %}
                        <input class="form-control me-2" type="search" placeholder="Введите отклик"
                               aria-label="Search"
                               name="content">
                        <button class="btn" style="background: #e53637; color: white;" type="submit">Отправить</button>
                    </form>
                </div>
            </div>
            <!-- Отзывы -->
            <div style="margin-top: 10px">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Отзывы</h3>
                    <div class="container" id="cart-items-container">

                        {% include 'includes/replies_post.html' %}

                    </div>
                </div>
            </div>

        </div>
    </article>
{% endblock content %}

templates/posts/post_edit.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ title_page }}
{% endblock title %}

{% block content %}
    <section id="post-add">
        <div class="container">
            <h3 style="color: white">{{ title_page }}</h3>
            <hr>
            <div>
                <div class="text-start mt-5">
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form.media }}
{#                        {{ form.as_p }}#}

                        <div class="col-md-12 mb-3 ">
                            <label for="id_category" class="form-label" style="color: white">Категория*</label>
                            <select id="id_category" name="category" required>
                                {% for category in categories %}
                                    <option value="{{ category.id }}"
                                            {% if post.category.id == category.id %}selected{% endif %}>
                                        {{ category.name }}
                                    </option>
                                {% endfor %}
                            </select>
                            {% if form.category.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.category.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="col-md-12 mb-3" style="color: white">
                            <label for="id_title" class="form-label">Заголовок:</label>
                            <input type="text" class="form-control" id="id_title"
                                   name="title"
                                   placeholder="Введите заголовок"
                                   value="{% if form.title.value %}{{ form.title.value }}{% endif %}"
                                   required>
                            {% if form.title.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.title.errors }}</div>
                            {% endif %}
                        </div>
                        {{ form.content }}
{#                        <div class="col-md-12 mb-3" style="color: white">#}
{#                            <label for="id_content" class="form-label">Содержание:</label>#}
{#                            <textarea name="content" class="form-control django_ckeditor_5"#}
{#                                      cols="40" rows="10" required id="id_content"#}
{#                                      placeholder="Введите текст публикации">#}
{#                                {{ form.content|safe }}#}
{#                            </textarea>#}
{#                            {% if form.content.errors %}#}
{#                                <div class="alert alert-danger alert-dismissible fade show">{{ form.content.errors }}</div>#}
{#                            {% endif %}#}
{#                        </div>#}
                        <button type="submit" class="btn btn-success">
                            <span class="glyphicon glyphicon-ok"></span>Сохранить
                        </button>
                        <a class="glyphicon glyphicon-ok" href="{{ request.META.HTTP_REFERER }}">Назад</a>
                    </form>
                </div>
            </div>

        </div>
    </section>

{% endblock content %}

templates/posts/post_list.html
{% extends 'base.html' %}
{% load cache %}
{% load static %}

{% block title %}
    Posts
{% endblock title %}

{% block content %}
    <!-- Hero Section Begin -->
    {% cache 60 news_list %}
        {% if news_list %}
            <section class="hero">
                <div class="container">
                    <div class="hero__slider owl-carousel">
                        {% for news in news_list %}

                            <div class="hero__items set-bg"
                                    {% if news.image %}
                                 data-setbg="{{ news.image.url }}"
                                    {% else %}
                                 data-setbg="{% static 'img/hero/hero-1.jpg' %}"
                                    {% endif %}>
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="hero__text">
                                            <h2 style="-webkit-text-stroke-width: 1px; -webkit-text-stroke-color: #0b0c2a">
                                                {{ news.title|truncatewords:20|safe }}
                                            </h2>
                                            <p>{{ news.content|truncatewords:20|safe }}</p>
                                            <a href="{% url 'posts:post_detail' news.id %}"><span>Подробней...</span>
                                                <i class="fa fa-angle-right"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        {% endfor %}
                    </div>
                </div>
            </section>
            <!-- Hero Section End -->

        {% endif %}
    {% endcache %}

    <section id="posts">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">

                    <div class="section-title">
                        {% if category %}
                            <h4>{{ category }}</h4>
                        {% else %}
                            <h4>{{ title }}</h4>
                        {% endif %}
                    </div>

                    {% include 'includes/in_posts.html' %}

                </div>
                <div class="section-title">
                    <h4>Принятые отзывы</h4>
                    <div style="margin-top: 25px">
                        {% include 'includes/replies_post.html' %}
                    </div>

                </div>
            </div>
        </div>
    </section>
    <!-- End Posts Section -->
    <footer class="footer">
        <div class="page-up">
            <a href="#" id="scrollToTopButton"><span class="arrow_carrot-up"></span></a>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="footer__logo">
                        <a href="/"><img src="{% static 'img/logo.png' %}" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="footer__nav">
                        <ul>
                            <li class="active"><a href="/">Главная</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3">
                    <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright ©
                        <script>document.write(new Date().getFullYear());</script>
                        2024
                        All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i>
                        by
                        <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>

                </div>
            </div>
        </div>
    </footer>
{% endblock content %}