fan_board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='home')),
    path('user/', include('users.urls', namespace='user')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
    path("", views.PostList.as_view(), name="index"),
    path('search/', views.PostList.as_view(), name='search'),
    path('post/post_create/', views.PostCreate.as_view(), name='post_create'),
    path('post/<int:post_id>/', views.PostDetail.as_view(), name="post_detail"),
    path('post/<int:post_id>/edit/', views.PostUpdate.as_view(), name='post_update'),
    path('post/<int:post_id>/delete/', views.PostDelete.as_view(), name="post_delete"),
    path('post/<int:id>/like/', views.post_like, name="post_like"),
    path('post/<int:id>/dislike/', views.post_dislike, name="post_dislike"),
    path('post/<int:post_id>/reply_add/', views.reply_add, name="reply_add"),
    path('replies/<int:reply_id>/reply_delete/', views.reply_delete, name="reply_delete"),
    path('replies/<int:reply_id>/reply_accept/', views.reply_accept, name="reply_accept"),
]

templates/includes/in_posts.html
{% load static %}
{% load custom_tags %}

{% if post_list %}
    {{ form.media }}
    {% for post in post_list %}
        <article>
            <div class="story__main" style="margin-top: 5px">
                <header class="story__header">
                    <div class="story__user">
                        <div class="story__user-info">
                            <a class="story__user-link user__nick" href="#">
                                <div class="avatar avatar_small">
                                    <span class="avatar__inner">
                                        {% if post.author.image %}
                                            <img src="{{ post.author.image.url }}" alt=""
                                                 class="image-loaded avatar avatar_small">
                                        {% else %}
                                            <img src="{% static 'img/baseavatar.jpg' %}" alt=""
                                                 class="image-loaded avatar avatar_small">
                                        {% endif %}
                                    </span>
                                </div>
                                {{ post.author }}
                            </a>
                            <div>
                                <time datetime="{{ post.created_at }}"
                                      class="caption story__datetime">{{ post.created_at }}
                                </time>
                            </div>
                            <a class="story__user-link user__nick"
                               href="{{ post.category.id }}">{{ post.category }}</a>
                        </div>
                    </div>
                    <h4 class="story__title">
                        <a href="{% url 'posts:post_detail' post.id %}">
                            {% if post.headline %}
                                {% autoescape off %}
                                    {{ post.headline }}
                                {% endautoescape %}
                            {% else %}
                                {{ post.title }}
                            {% endif %}
                        </a>
                    </h4>
                </header>
                <div class="story__content-wrapper">
                    <div class="story__content story__typography" style="display: block">
                        <div class="story__content-inner">
                            <div class="story-block story-block_type_text">
                                <p>
                                    {% if post.bodyline %}
                                        {% autoescape off %}
                                            {{ post.bodyline|truncatewords:20|safe }}
                                        {% endautoescape %}
                                    {% else %}
                                        {{ post.content|truncatewords:20|safe }}
                                    {% endif %}
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="story__footer">
                        <div class="story__tools" style="font-size: 1rem; line-height: 1.5;">
                            <div class="comment">
                                <a style="color: var(--color-black-700);"
                                   href="{% url 'posts:post_detail' post.id %}#replies">
                                    <i class="fa fa-comments"></i>
                                    <span style="margin-left: 10px; line-height: 15px;"> {{ post.get_reply_count }} </span>
                                </a>
                            </div>
                            <div class="view">
                                <i style="margin-left: 10px;" class="fa fa-eye"></i>
                                <span style="margin-left: 10px; line-height: 15px;"
                                      class="story__views-count">{{ post.get_view_count }}</span>
                            </div>
                            <div>
                                <a style="color: var(--color-black-700);"
                                   href="post/{{ post.id }}/like/">
                                    <i style="margin-left: 10px;" class="fa fa-caret-up"></i>
                                    <span style="margin-left: 5px;">{{ post.rating }}</span>
                                </a>

                            </div>
                            <div>
                                <a style="color: var(--color-black-700);"
                                   href="post/{{ post.id }}/dislike/">
                                    <i style="margin-left: 10px;" class="fa fa-caret-down"></i>
                                </a>
                            </div>
                        </div>
                        <div>
                            <a href="{% url 'posts:post_detail' post.id %}">Просмотреть</a>
                        </div>
                    </div>
                </div>
            </div>
        </article>

    {% endfor %}
    <div class="padding" style="text-align: center; color: white">
        <!-- Пагинация -->
        {# Добавляем пагинацию на страницу #}

        {# Переход к 1 странице #}
        <a title="Первая страница" href="?{% url_replace page=1 %}"> << </a>

        {% if page_obj.has_previous %}
            {# Для каждой ссылки пагинации указываем обработку через новый тег #}
            <a href="?{% url_replace page=1 %}">1</a>
            {% if page_obj.previous_page_number != 1 %}
                ...
                <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
            {% endif %}
        {% endif %}

        {{ page_obj.number }}

        {% if page_obj.has_next %}
            <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
            {% if paginator.num_pages != page_obj.next_page_number %}
                ...
                <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
            {% endif %}
        {% endif %}

        {# Переход к последней странице #}
        <a href="?{% url_replace page=page_obj.paginator.num_pages %}"> >> </a>
    </div>
{% else %}
    <h2 style="color: white">Публикаций нет!</h2>
{% endif %}

templates/includes/replies_post.html
{% load static %}
{% load custom_tags %}

<section class="comments" style="padding: 5px">
    <div class="comments__container">
        {% for reply in replies %}
            <div class="comment" style="background: #f2f2f2; font-size: 20px">
                <div class="comment__body" style="display: flex">
                    <div>
                        <div class="comment__user" style="display: inline">
                            <a class="user" href="#" target="_blank">
                                {% if reply.author.image %}
                                    <img src="{{ reply.author.image.url }}" alt=""
                                         class="image-loaded avatar avatar_small">
                                {% else %}
                                    <img src="{% static 'img/baseavatar.jpg' %}" alt=""
                                         class="image-loaded avatar avatar_small">
                                {% endif %}
                            </a>
                            <a href="#" target="_blank">
                                        <span class="comment__content">
                                            {{ reply.author }}
                                        </span>
                            </a>
                        </div>
                        <div style="display: inline">
                            <time datetime="{{ reply.created_at }}"
                                  class="comment__datetime"
                                  style="margin-left: 8px;">{{ reply.created_at }}</time>
                        </div>
                    </div>
                    {% if show_add_button %}
                        <div style="margin-left: auto;">
                            {% if reply.is_accepted %}
                                <a class="btn" href="#">✔</a>
                            {% else %}
                                <a style="color: var(--color-black-700);"
                                   href="{% url 'posts:reply_accept' reply.id %}">
                                    Принять
                                </a>
                            {% endif %}
                            <a style="color: var(--color-black-700);"
                               href="{% url 'posts:reply_delete' reply.id %}">Удалить</a>
                        </div>
                    {% endif %}
                </div>
                <div class="comment__content">
                    {% if is_profile %}
                        <a href="?post_filter={{ reply.post.id }}" style="font-size: 15px; color: #0b0c2a">
                            <img src="{% static 'img/filter.png' %}" alt="" width="15"
                                 title="Фильтровать отзывы по этой публикации">
                            {{ reply.post|truncatechars:30 }}
                        </a>
                    {% else %}
                        <a href="{% url 'posts:post_detail' reply.post.id %}" style="font-size: 15px; color: #0b0c2a">
                            {{ reply.post|truncatechars:30 }}
                        </a>
                    {% endif %}
                    <p>{{ reply.content }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="padding" style="text-align: center; color: white">
        <!-- Пагинация -->
        {% if replies and show_add_button %}
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center my-4">
                    <div class="custom-shadow d-flex">

                        <li class="page-item {% if not replies.has_previous %}disabled{% endif %}">
                            <a class="page-link" href="{% if replies.has_previous %}?
                                {% change_params page=replies.previous_page_number %}{% else %}#{% endif %}">Назад</a>
                        </li>

                        {% for page in replies.paginator.page_range %}
                            {% if page >= replies.number|add:-2 and page <= replies.number|add:2 %}
                                <li class="page-item {% if replies.number == page %} active {% endif %}">
                                    <a class="page-link" href="?{% change_params page=page %}">{{ page }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}

                        <li class="page-item {% if not replies.has_next %}disabled{% endif %}">
                            <a class="page-link" href="{% if replies.has_next %}?
                                {% change_params page=replies.next_page_number %}{% else %}#{% endif %}">Следующая</a>
                        </li>
                    </div>
                </ul>
            </nav>
        {% endif %}
    </div>

</section>