fan_board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='home')),
    path('user/', include('users.urls', namespace='user')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
    path("", views.PostList.as_view(), name="index"),
    path('search/', views.PostList.as_view(), name='search'),
    path('post/post_create/', views.PostCreate.as_view(), name='post_create'),
    path('post/<int:post_id>/', views.PostDetail.as_view(), name="post_detail"),
    path('post/<int:post_id>/edit/', views.PostUpdate.as_view(), name='post_update'),
    path('post/<int:post_id>/delete/', views.PostDelete.as_view(), name="post_delete"),
    path('post/<int:id>/like/', views.post_like, name="post_like"),
    path('post/<int:id>/dislike/', views.post_dislike, name="post_dislike"),
    path('post/<int:post_id>/reply_add/', views.reply_add, name="reply_add"),
    path('replies/<int:reply_id>/reply_delete/', views.reply_delete, name="reply_delete"),
    path('replies/<int:reply_id>/reply_accept/', views.reply_accept, name="reply_accept"),
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('request_code/<str:username>/', views.request_code, name='request_code'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ru">

{% load static %}
{% load custom_tags %}
{% load cache %}

{% get_all_category as categories %}

<head>
    <meta charset="utf-8">

    <meta charset="UTF-8">
    <meta name="description" content="Anime Template">
    <meta name="keywords" content="Anime, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MMORPG board</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap"
          rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/plyr.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">

    <!-- Template Main CSS File -->
    <link href="{% static 'css/app.css' %}" rel="stylesheet">
    
    <!-- CKEditor 5 -->
    <script async charset="utf-8" src="//cdn.embedly.com/widgets/platform.js"></script>

</head>

<body>

<!-- Page Preloder -->
<div id="preloder">
    <div class="loader"></div>
</div>
<!-- Header Section Begin -->
<header class="header">
    <div class="container">
        <div class="row">
            <div class="col-lg-2">
                <div class="header__logo">
                    <a href="{% url 'posts:index' %}">
                        <img src="{% static 'img/logo.png' %}" alt="">
                    </a>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="header__nav">
                    <nav class="header__menu mobile-menu">
                        <ul>
                            <li><a href="{% url 'posts:index' %}">Главная</a></li>
                            <li><a href="#">Категории<span class="arrow_carrot-down"></span></a>
                                <ul class="dropdown">
                                    {% for category in categories %}
                                        <li><a href="/?category={{ category.id }}">{{ category.name }}</a></li>
                                    {% endfor %}
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>

            <div class="col-lg-2">
                <div class="header__nav">
                    <nav class="header__menu mobile-menu">
                        <ul>
                            {% if not user.is_authenticated %}
                                <li class="active"><a href="{% url 'user:login' %}">Вход</a></li>
                            {% else %}
                                <li><a href="#"><span class="icon_profile"></span></a>
                                    <ul class="dropdown">
                                        <li style="text-align: center" class="active">
                                            <strong>{{ user.username }}</strong>
                                        </li>
                                        <li><a href="{% url 'posts:post_create' %}">
                                            <span class="icon_plus"></span>Добавить</a>
                                        </li>
                                        <li><a href="{% url 'user:profile' %}">Личный кабинет</a></li>
                                        <br>
                                        <li><a href="{% url 'user:logout' %}">Выход</a></li>
                                    </ul>
                                </li>
                            {% endif %}


                        </ul>
                    </nav>
                </div>
            </div>
        </div>
        <div id="mobile-menu-wrap"></div>
        <div class="header__bottom">
            <form role="search" action="#" method="get">
                <input type="search" name="q" placeholder="Поиск" aria-label="Поиск">
                <button class="btn btn-outline-success text-white" type="submit">
                    <span class="icon_search">
                </button>
            </form>
        </div>

    </div>

</header>
<!-- Header End -->

{% block content %}
{% endblock content %}



<!-- Js Plugins -->
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/player.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/mixitup.min.js' %}"></script>
<script src="{% static 'js/jquery.slicknav.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

<!-- CKEditor -->
<script>
    document.querySelectorAll( 'oembed[url]' ).forEach( element => {
        // Create the <a href="..." class="embedly-card"></a> element that Embedly uses
        // to discover the media.
        const anchor = document.createElement( 'a' );

        anchor.setAttribute( 'href', element.getAttribute( 'url' ) );
        anchor.className = 'embedly-card';

        element.appendChild( anchor );
    } );
</script>
</body>

</html>