fan_board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='home')),
    path('user/', include('users.urls', namespace='user')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
    path("", views.PostList.as_view(), name="index"),
    path('search/', views.PostList.as_view(), name='search'),
    path('post/post_create/', views.PostCreate.as_view(), name='post_create'),
    path('post/<int:post_id>/', views.PostDetail.as_view(), name="post_detail"),
    path('post/<int:post_id>/edit/', views.PostUpdate.as_view(), name='post_update'),
    path('post/<int:post_id>/delete/', views.PostDelete.as_view(), name="post_delete"),
    path('post/<int:id>/like/', views.post_like, name="post_like"),
    path('post/<int:id>/dislike/', views.post_dislike, name="post_dislike"),
    path('post/<int:post_id>/reply_add/', views.reply_add, name="reply_add"),
    path('replies/<int:reply_id>/reply_delete/', views.reply_delete, name="reply_delete"),
    path('replies/<int:reply_id>/reply_accept/', views.reply_accept, name="reply_accept"),
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('request_code/<str:username>/', views.request_code, name='request_code'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """
    Добавляем пользователю поле Подписан на рассылку новостей
    """
    is_subscribed = models.BooleanField(default=False, verbose_name='Подписан на рассылку новостей')
    image = models.ImageField(upload_to='user_images', blank=True, null=True, verbose_name='Аватар')

    def __str__(self):
        return self.username


class OneTimeCode(models.Model):
    """
    Код для отправки письма с кодом регистрации
    """
    code = models.CharField(max_length=10, verbose_name='Код')
    user = models.ForeignKey(User, related_name='Пользователь', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Код подтверждения регистрации'
        verbose_name_plural = 'Коды подтверждения регистрации'

    def __str__(self):
        return f'{self.user.username}: {self.code}'

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

    username = forms.CharField()
    password = forms.CharField()

    # username = forms.CharField(
    #     label = 'Имя',
    #     widget=forms.TextInput(attrs={"autofocus": True,
    #                                   'class': 'form-control',
    #                                   'placeholder': 'Введите ваше имя пользователя'})
    # )
    # password = forms.CharField(
    #     label = 'Пароль',
    #     widget=forms.PasswordInput(attrs={"autocomplete": "current-password",
    #                                       'class': 'form-control',
    #                                       'placeholder': 'Введите ваш пароль'})
    # )


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "password1",
            "password2",
        )

    username = forms.CharField()
    email = forms.CharField()
    # first_name = forms.CharField()
    # last_name = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

    # first_name = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введите ваше имя",
    #         }
    #     )
    # )
    # last_name = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введите вашу фамилию",
    #         }
    #     )
    # )
    # username = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введите ваше имя пользователя",
    #         }
    #     )
    # )
    # email = forms.CharField(
    #     widget=forms.EmailInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введите ваш email *youremail@example.com",
    #         }
    #     )
    # )
    # password1 = forms.CharField(
    #     widget=forms.PasswordInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введите ваш пароль",
    #         }
    #     )
    # )
    # password2 = forms.CharField(
    #     widget=forms.PasswordInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Поддтвердите ваш пароль",
    #         }
    #     )
    # )


class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "last_name",
            "username",
            "email",)

    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

    # image = forms.ImageField(
    #     widget=forms.FileInput(attrs={"class": "form-control mt-3"}), required=False
    # )
    # first_name = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введите ваше имя",
    #         }
    #     )
    # )
    # last_name = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введите вашу фамилию",
    #         }
    #     )
    # )
    # username = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введите ваше имя пользователя",
    #         }
    #     )
    # )
    # email = forms.CharField(
    #     widget=forms.EmailInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введите ваш email *youremail@example.com",
    #             # 'readonly': True,
    #         }
    #     ),
    # )


class RequestCodeForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'code']

    username = forms.CharField()
    code = forms.CharField()

users/views.py
from django.core.paginator import Paginator
from django.shortcuts import redirect, render
from django.contrib import auth, messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from posts.models import Reply, Post
from posts.utils import generate_code
from users.forms import UserLoginForm, UserRegistrationForm, ProfileForm, RequestCodeForm
from users.models import OneTimeCode, User


def login(request):
    error = ''
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)

            if user:
                if OneTimeCode.objects.filter(user=user).exists():
                    return HttpResponseRedirect(reverse('user:request_code', args=(username,)))
                else:
                    auth.login(request, user)
                    messages.success(request, f"{username}, Вы вошли в аккаунт")
                    return HttpResponseRedirect(reverse('posts:index'))
            else:
                error = 'Неверный логин или пароль'
                messages.error(request, error)
    else:
        form = UserLoginForm()

    context = {
        'title': 'Home - Авторизация',
        'form': form,
    }
    return render(request, 'users/login.html', context)


@login_required
def logout(request):
    # messages.success(request, f"{request.user.username}, Вы вышли из аккаунта")
    auth.logout(request)
    return redirect(reverse('posts:index'))


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            # Запись пользователя
            form.save()
            user = form.instance

            # Запись пользователя в таблицу с одноразовым кодом
            _code = generate_code()
            one_time_code = OneTimeCode.objects.create(user=user, code=_code)

            # Отправка одноразового кода на емайл, запущена через сигналы
            # send_mail_onetime_code(username=user.username, code=_code)

            messages.success(
                request,
                f"{user.username}, Вам на почту отправлено письмо с кодом подтверждения регистрации, проверьте почту"
            )
            return HttpResponseRedirect(reverse('user:request_code', args=(user.username,)))

    else:
        form = UserRegistrationForm()

    context = {
        'title': 'Регистрация',
        'form': form,
    }
    return render(request, 'users/registration.html', context)


@login_required
def profile(request):
    page = request.GET.get("page", 1)
    page_reply = request.GET.get("page_reply", 1)
    post_filter = request.GET.get("post_filter", None)

    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Личные данные успешно сохранены")
            return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = ProfileForm(instance=request.user)

    # отзывы
    if post_filter:
        replies = Reply.objects.filter(post__author=request.user, post_id=post_filter).order_by('-created_at')
        post = Post.objects.get(id=post_filter)
    else:
        replies = Reply.objects.filter(post__author=request.user).order_by('-created_at')
    pagination = Paginator(replies, 5)
    current_page = pagination.page(int(page_reply))

    posts = Post.objects.filter(author=request.user)
    pagination_posts = Paginator(posts, 5)
    current_page_posts = pagination_posts.page(int(page))

    context = {
        'title': 'Home - Кабинет',
        'form': form,
        'replies': current_page,
        'page_obj': pagination,
        'show_add_button': True,
        'post_list': current_page_posts,
        'is_profile': True
    }
    if post_filter:
        context['post'] = post

    return render(request, 'users/profile.html', context)


def request_code(request, *args, **kwargs):
    """
    Проверка кода подтверждения регистрации
    """

    error = ''
    username = kwargs.get('username')

    if request.method == 'POST':
        form = RequestCodeForm(data=request.POST)
        username = request.POST.get('username')
        code = request.POST.get('code')

        user = User.objects.get(username=username)
        if user:
            one_time_code = OneTimeCode.objects.filter(code=code, user=user)

            if one_time_code.exists():
                # Авторизация пользователя
                auth.login(request, user)

                # Уничтожение кода
                one_time_code.delete()

                return HttpResponseRedirect(reverse('posts:index'))

            else:
                error = 'Неверный код подтверждения регистрации'
                messages.error(request, error)
        else:
            error = 'Неверно имя пользователя'
            messages.error(request, error)
    else:
        form = RequestCodeForm()

    context = {
        'form': form,
        'title': 'Подтверждение регистрации',
        'error': error,
        'username': username,
    }

    return render(request, 'users/request_code.html', context)

templates/users/accept_replay.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Изменился статус вашего отзыва</title>
</head>
<body>
<section>
    <p>Здравствуй {{ username }}.</p>
    <hr>
    <p>Ваш отзыв на публикацию:</p>
    <a href="{% url 'posts:post_detail' post.id %}">{{ post.title }}</a>
    <hr>
    {% if is_accepted %}
        <h3>Принят</h3>
    {% else %}
        <h3>Не принят</h3>
    {% endif %}
    <hr>
    <p>{{ content }}</p>
</section>
</body>
</html>

templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Users
{% endblock title %}

{% block content %}
    <section class="normal-breadcrumb set-bg" data-setbg="{% static 'img/normal-breadcrumb.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="normal__breadcrumb__text">
                        <h2>Авторизоваться</h2>
                        <p>Добро пожаловать на наш сайт</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="login spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="login__form">
                        <h3>Авторизация</h3>
                        <form action="{% url 'user:login' %}" method="post">
                            {% csrf_token %}
                            <div class="input__item">
                                <input type="text" class="form-control"
                                       value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                                       name="username" id="id_username"
                                       placeholder="Введите ваше имя пользователя"
                                       required>
                                <span class="icon_mail"></span>
                            </div>
                            <div class="input__item">
                                <input type="password" class="form-control" name="password" id="id_password"
                                       placeholder="Введите ваш пароль" required>
                                <span class="icon_lock"></span>
                            </div>
                            {% if form.error_messages %}
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <div class="alert alert-danger" role="alert">
                                            {{ error }}
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                                {% for error in form.non_field_errors %}
                                    <div class="alert alert-danger" role="alert">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <button type="submit" class="site-btn">Войти</button>
                        </form>
                        <a href="#" class="forget_pass">Забыли пароль?</a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="login__register">
                        <h3>У вас нет учетной записи?</h3>
                        <a href="{% url 'user:registration' %}" class="primary-btn">Зарегистрироваться</a>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

templates/users/message_week_post.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Уведомление.</title>
</head>
<body>
<h2>Здравствуйте {{ user_ }}, новые статьи за последнюю неделю</h2>
<hr>
<p>Категории подписки:</p>
{% for cat in cat_users %}
    <a>{{ cat }}, </a>
{% endfor %}
{% for post in posts_user %}
    <p><a href="{{ SITE_URL }}/news/{{ post.pk }}"> {{ post.title }}</a></p>
{% endfor %}

</body>
</html>

templates/users/new_replay.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Новый отзыв</title>
</head>
<body>
<section>
    <p>Здравствуй {{ username }}.</p>
    <hr>
    <p>На вашу публикацию</p>
    <a href="{% url 'posts:post_detail' post.id %}">{{ post.title }}</a>
    <p>получен новый отзыв</p>
    <hr>
    <p>{{ content }}</p>
</section>
</body>
</html>

templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="container mt-5">
            <div class="row">
                <!-- Профиль с данными пользователя -->
                <div class="col-md-5">
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">Профиль пользователя</h3>
                        <form action="{% url "user:profile" %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12 mb-3 text-center">
                                    {% if user.image %}
                                        <img src="{{ user.image.url }}"
                                             alt="Аватар пользователя" class="img-fluid rounded-circle"
                                             style="max-width: 150px;">
                                    {% else %}
                                        <img src="{% static "img/baseavatar.jpg" %}"
                                             alt="Аватар пользователя" class="img-fluid rounded-circle"
                                             style="max-width: 150px;">
                                    {% endif %}
                                    <input type="file" class="form-control mt-3" id="id_image"
                                           name='image'
                                           accept="image/*">
                                    {% if form.image.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.image.errors }}</div>
                                    {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_first_name" class="form-label">Имя*</label>
                                    <input type="text" class="form-control" id="id_first_name"
                                           name="first_name"
                                           placeholder="Введите ваше имя"
                                           value="{{ form.first_name.value }}"
                                           required>
                                    {% if form.first_name.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                    {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_last_name" class="form-label">Фамилия*</label>
                                    <input type="text" class="form-control" id="id_last_name"
                                           name="last_name"
                                           placeholder="Введите вашу фамилию"
                                           value="{{ form.last_name.value }}"
                                           required>
                                    {% if form.last_name.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                    {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_username" class="form-label">Имя пользователя*</label>
                                    <input type="text" class="form-control" id="id_username"
                                           name="username"
                                           placeholder="Введите ваше имя пользователя"
                                           value="{{ form.username.value }}"
                                           required>
                                    {% if form.username.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                    {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_email" class="form-label">Email*</label>
                                    <input type="email" class="form-control" id="id_email"
                                           name="email"
                                           placeholder="Введите ваш email *youremail@example.com"
                                           value="{{ form.email.value }}"
                                           required>
                                    {% if form.email.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                    {% endif %}
                                </div>
                            </div>
                            <button type="submit" class="btn btn-dark">Сохранить</button>
                        </form>
                    </div>
                </div>
                <!-- Отзывы -->
                <div class="col-md-7">
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">Отзывы</h3>
                        <div class="container" id="cart-items-container">
                            {% if post %}
                                {{ post.title }}
                                <a href="{% url 'user:profile' %}">X</a>
                            {% endif %}

                            {% include 'includes/replies_post.html' %}

                        </div>
                    </div>
                </div>
                <!-- Публикации -->
                <div class="col-md-12">
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">Мои публикации</h3>
                        <div class="container">
                            <div class="accordion" id="accordionExample">
                                {% include 'includes/in_posts.html' %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/registration.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Users registration
{% endblock title %}
{% block content %}
    <!-- Normal Breadcrumb Begin -->
    <section class="normal-breadcrumb set-bg" data-setbg="{% static 'img/normal-breadcrumb.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="normal__breadcrumb__text">
                        <h2>{{ title }}</h2>
                        <p>Добро пожаловать</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Normal Breadcrumb End -->

    <!-- Signup Section Begin -->
    <section class="signup spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="login__form">
                        <h3>Регистрация</h3>
                        <form action="{% url 'user:registration' %}" method="post">
                            {% csrf_token %}
                            <div class="input__item">
                                <input type="text"
                                       value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                                       placeholder="Email address"
                                       name="email"
                                       required
                                >
                                <span class="icon_mail"></span>
                                {% if form.email.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="input__item">
                                <input type="text"
                                       value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                                       placeholder="Введите имя"
                                       name="username"
                                       required
                                >
                                <span class="icon_profile"></span>
                                {% if form.username.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="input__item">
                                <input type="password" placeholder="Пароль" name="password1">
                                <span class="icon_lock"></span>
                                {% if form.password1.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.password1.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="input__item">
                                <input type="password" placeholder="Подтвердите пароль" name="password2">
                                <span class="icon_lock"></span>
                                {% if form.password2.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.password2.errors }}</div>
                                {% endif %}
                            </div>
                            <button type="submit" class="site-btn">Зарегистрироваться</button>
                        </form>
                        <h5>Вы уже зарегистрированы? <a href="{% url 'user:login' %}">Войдите!</a></h5>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="login__social__links">
                        <h3>Информация:</h3>
                        <p style="color: white">Вам на почту будет оправлен код подтверждения регистрации.</p>
                        <p style="color: white">Проверяйте почту.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Signup Section End -->


{% endblock content %}

templates/users/request_code.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Users
{% endblock title %}

{% block content %}
    <section class="normal-breadcrumb set-bg" data-setbg="{% static 'img/normal-breadcrumb.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="normal__breadcrumb__text">
                        <h2>{{ title }}</h2>
                        <p>Добро пожаловать на наш сайт</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="login spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="login__form">
                        <h3>{{ title }}</h3>
                        <form action="{% url 'user:request_code' username %}" method="post">
                            {% csrf_token %}
                            <div class="input__item">
                                <input type="text" class="form-control" style="color: #0b0c2a"
                                       value="{% if form.username.value %}{{ form.username.value }}{% else %}{{ username }}{% endif %}"
                                       name="username" id="id_username"
                                       placeholder="Введите ваше имя пользователя"
                                       required>
                                <span class="icon_mail"></span>
                            </div>
                            <div class="input__item">
                                <input type="text" class="form-control" name="code" id="id_code" style="color: #0b0c2a"
                                       placeholder="Введите код подтверждения регистрации" required>
                                <span class="icon_lock"></span>
                            </div>
                            {% if error %}
                                <div class="alert alert-danger" role="alert">
                                    {{ error }}
                                </div>
                            {% endif %}
                            {% if form.error_messages %}
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <div class="alert alert-danger" role="alert">
                                            {{ error }}
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                                {% for error in form.non_field_errors %}
                                    <div class="alert alert-danger" role="alert">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            {% endif %}

                    <button type="submit" class="site-btn">Войти</button>
                    </form>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="login__register">
                    <h3>Информация:</h3>
                    <p style="color: white">На ваш e-mail был выслан код подтверждения.</p>
                    <p style="color: white">Проверьте почту.</p>
                </div>
            </div>
        </div>
        </div>
    </section>

{% endblock content %}